### ISSUE TITLE
p-value 'zero' and z-score 'infinity' ?

### ISSUE THREAD

**Issue by drveera** [hakyimlab/MetaXcan#53]
Hi Haky,

How to interpret the result, if p value is zero and z-score is infinity? 

Thanks 

-Veera

**Comment by Heroico** [comment]
Hi Veera,

`p-value=0` and `zscore=inf` arise due to precision errors in floating point operations,
and/or resolution in scipy's `normal distribution cumulative distribution function`.
It basically means that the implementation tried to do math beyond floating point resolution.
On our analysis we are currently discarding these kinds of results, but we are looking into ways to improve resolution.

**Comment by hakyim** [comment]
Discarding these cases is probably not a good idea. They should be flagged and investigated whether the p=0 arise because of numerical rounding or because of misspecified variances. In general if there are a few SNPs in the models that have significant GWAS pvalues, I would tend to trust that the association is real.

**Comment by drveera** [comment]
@hakyim @Heroico thanks for your inputs.
