### ISSUE TITLE
covariance file LD panel

### ISSUE THREAD

**Issue by gpwhiz** [hakyimlab/MetaXcan#98]
Hello!
Can you please clarify if the covariance file provided on Zenodo was made with all five populations of 1000G and not just EUR. I read it in the first paper of MetaXcan, but I still wanted to confirm. If not can you provide reference for EAS population. My goal is to predict gene expression for EAS summary stats.
Thank you for developing this approach, its great work.

**Comment by Heroico** [comment]
Good day,

The prediction models trained on GTEx data use LD from GTEx European individuals. LD from 1000G is not used.

For completeness-sake, in the MetaXcan paper: we used 1000G references from EAS, AFR, EUR populations only to showcase the cross-population effect. 1000G was used only in this sub-analysis. 
Also, please note that the model-building scheme evolved since the MetaXcan paper. 

In general, tools from the MetaXcan family use LD from the same data where models were trained.
i.e. If a model was trained on GTEx European individuals, then those same individuals are used for the LD computation. This is more robust than using LD from a 3rd data set, since the models use the same LD structure they learned in; e.g. it's better to use GTEx Europeans than 1000G Europeans.

If you want to use EAS LD applied to EAS GWAS summary statistics, you can indeed generate EAS LD from 1000G. The models are sqlite databases that you can open programmatically (example in R [here](https://github.com/hakyimlab/PrediXcan/blob/master/Software/query-db.Rmd) For each gene, you would need to retrieve to list the variants, then compute their covariances from 1000G EAS genotypes.

**Comment by gpwhiz** [comment]
Thank you for your response. Would you be able to provide link to the script used in MetaXcan for deriving covariance. I saw that covariance.py scripts show deprecated next to them, which is why I am asking. I am still new to calculating my own study specific weights.

**Comment by Heroico** [comment]
Hi there,

*M01_covariances_correlations.py* is deprecated but still works and people have used it to generate LD panels from existing models using separate cohorts of genotypes. Feel free to use it.

We deprecated it because covariances are generated at the same step of the model training.
The new model training code is [here](https://github.com/hakyimlab/PredictDB_Pipeline_GTEx_v7)
And it's explained [here](https://groups.google.com/forum/#!searchin/predixcanmetaxcan/using$20custom$20data%7Csort:date/predixcanmetaxcan/TkBxYkUpNGw/5O-J342qBAAJ).

Best,

Alvaro
